### ISSUE TITLE
Use better stack for this scraper

### ISSUE THREAD

**Issue by ErikBoesen** [FIRSTMap/scraper#7]
I would prefer to use a better language for this program than simply gawk and bash. My choice would be Python. This is not very high priority but maybe something to look into in the future.

**Comment by FishDog5000** [comment]
I am willing to convert it to Python. I have looked at the AWK scripts and I think I have a good grasp of how everything works.

**Comment by ErikBoesen** [comment]
@FishDog5000 godspeed
